# Generated by Django 4.2.6 on 2023-10-20 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageModel',
            fields=[
                ('message', models.TextField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('block', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('bio', models.CharField(max_length=80)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('block', models.BooleanField(default=False)),
                ('last_name', models.CharField(max_length=70)),
                ('first_name', models.CharField(max_length=70)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(max_length=70, unique=True)),
                ('phone', models.CharField(max_length=30, unique=True)),
                ('image', models.ImageField(default='images/user.png', upload_to='user/')),
            ],
        ),
    ]
