# Generated by Django 4.2.6 on 2023-10-20 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagemodel',
            name='from_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='from_id', to='users.usermodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='to_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='to_id', to='users.usermodel'),
            preserve_default=False,
        ),
    ]
