# Generated by Django 4.2.6 on 2023-10-20 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_messagemodel_from_id_messagemodel_to_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='image',
            field=models.ImageField(upload_to='image'),
        ),
    ]
